# Generated by Django 3.1.2 on 2020-10-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatacc', '0002_auto_20201030_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='external_id',
            field=models.PositiveIntegerField(unique=True, verbose_name='ID of the user at the social network'),
        ),
    ]
