# Generated by Django 3.1.2 on 2020-10-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatacc', '0003_auto_20201030_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='external_id',
            field=models.PositiveIntegerField(verbose_name='ID of the user at the social network'),
        ),
    ]
